# Generated by Django 5.0.2 on 2024-02-26 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=100)),
                ('phone', models.IntegerField(null=True)),
                ('info_animal', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=100)),
                ('register_date', models.DateField(auto_now_add=True)),
                ('img', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CardAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_animal', models.CharField(max_length=100)),
                ('info_animal', models.CharField(max_length=300)),
                ('img_animal', models.FileField(upload_to='')),
                ('register_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('worker', models.CharField(choices=[('0', 'Работник службы'), ('1', 'Работник ОМСУ')], max_length=100)),
                ('register_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app_OMSU.application')),
                ('info', models.CharField(max_length=300)),
                ('register_date', models.DateField(auto_now_add=True)),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_OMSU.cardanimal')),
            ],
        ),
    ]
